[project]
name = "pyautocomplete"
version = "2.0.0"
description = "Autocomplete written in python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "coverage>=7.9.2",
    "pytest>=8.4.1",
    "pytest-timeout>=2.4.0",
]
